#!/usr/bin/env python3
"""Generate the documentation changelog page from the GitHub releases.

The GitHub releases are the source of truth for release notes
(auto-generated from pull requests and curated in the GitHub UI).
This script fetches them from the GitHub API and renders
``docs/docs/changelog.md``.

Set the ``GITHUB_TOKEN`` environment variable to raise the API rate limit
(done automatically in CI).
"""

import json
import os
import re
import sys
import urllib.request
from pathlib import Path

REPO = "opengisch/pum"
OUTPUT = Path(__file__).parent / "docs" / "changelog.md"

HEADER = """<!-- This page is generated by docs/update_changelog_docs.py from the GitHub releases. Do not edit manually. -->

# Changelog

This page lists all PUM releases with their release notes, sourced from the
[GitHub releases](https://github.com/opengisch/pum/releases).

"""

PR_URL_RE = re.compile(rf"(?<!\()https://github\.com/{REPO}/pull/(\d+)")
COMPARE_URL_RE = re.compile(rf"(?<!\()https://github\.com/{REPO}/compare/([^\s)]+)")
HEADING_RE = re.compile(r"^#{1,4} +(.+?)\s*$", flags=re.MULTILINE)


def fetch_releases() -> list[dict]:
    """Fetch all releases (paginated) from the GitHub API."""
    releases = []
    page = 1
    while True:
        request = urllib.request.Request(
            f"https://api.github.com/repos/{REPO}/releases?per_page=100&page={page}",
            headers={"Accept": "application/vnd.github+json"},
        )
        token = os.environ.get("GITHUB_TOKEN")
        if token:
            request.add_header("Authorization", f"Bearer {token}")
        with urllib.request.urlopen(request) as response:
            batch = json.load(response)
        if not batch:
            return releases
        releases.extend(batch)
        page += 1


def render_body(release: dict) -> str:
    """Render a release body as Markdown suitable for the documentation page."""
    body = (release.get("body") or "").replace("\r\n", "\n").strip()
    if not body:
        return (
            f"See the [release page]({release['html_url']}) "
            f"and the [commit history](https://github.com/{REPO}/commits/{release['tag_name']})."
        )
    # Turn headings into bold text so only the version headings
    # appear in the page table of contents.
    body = HEADING_RE.sub(r"**\1**", body)
    # Shorten bare pull request and compare URLs.
    body = PR_URL_RE.sub(rf"[#\1](https://github.com/{REPO}/pull/\1)", body)
    body = COMPARE_URL_RE.sub(rf"[\1](https://github.com/{REPO}/compare/\1)", body)
    return body


def main() -> int:
    releases = fetch_releases()
    if not releases:
        print("No releases found, not updating the changelog page.", file=sys.stderr)
        return 1

    parts = [HEADER]
    for release in releases:
        if release.get("draft"):
            continue
        tag = release["tag_name"]
        date = (release.get("published_at") or release.get("created_at", ""))[:10]
        suffix = " (pre-release)" if release.get("prerelease") else ""
        parts.append(f"## [{tag}]({release['html_url']}) - {date}{suffix}\n")
        parts.append(render_body(release) + "\n")

    OUTPUT.write_text("\n".join(parts))
    print(f"Wrote {len(releases)} releases to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
