name: 🪟 Winows Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Testing Windows

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        pg_major: [14]

    runs-on: ${{ matrix.os }}

    env:
      PGSYSCONFDIR: .

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Start PostgreSQL ${{ matrix.pg_major }} (Windows)
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: postgres
          password: postgres
          database: postgres
          port: 5432
          postgres-version: "${{ matrix.pg_major }}"

      - name: Install dependencies
        run: |
          python -m pip install -r requirements/base.txt
          python -m pip install -r requirements/development.txt
          python -m pip install -r requirements/html.txt

      - name: Install pum
        run: python -m pip install .

      - name: Setup db
        shell: bash
        run: ./.ci/setup_db.sh

      - name: Run base tests
        run: nose2 -v

      - name: Run dump and restore tests
        shell: bash
        run: ./test/test_dump_restore.sh

      # - name: Run migrations tests
      #   shell: bash
      #   run: ./test/test_pum.sh
